[package]
name = "cm-sim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smol = "1.3.0"
oneshot = "0.1.6"
nalgebra = "0.32.3"
